server:
  port: 80
logging:
  path: /java/log
  level: error
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.0.0.111:3306/barrage?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
  data:
    solr:
      host: http://1.0.0.111:8983/solr/core
  redis:
      database: 0
      host: localhost
      port: 6379
      timeout: -1