server:
  port: 8081
logging:
  path: /java/log
  level: error
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.0.0.111:3306/barrage_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#  data:
#    solr:
#      host: http://1.0.0.111:8983/solr/core
  redis:
      database: 0
      host: localhost
      port: 6379
      timeout: -1
#  activemq:
##  管理界面：8161 tcp：61616
#    broker-url: tcp://1.0.0.111:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: false
